# Generated by Django 5.1.15 on 2026-09-09 06:55

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MachineType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. TIPPING, SPINDLE, CH SPINDLE, WINDER, SMALL WINDER', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('maintenance_interval_days', models.PositiveIntegerField(default=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UtilityEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Excel NAME OF UT e.g. DRILL, GRINDER, MIZAN', max_length=100)),
                ('category', models.CharField(default='GENERAL', max_length=50)),
                ('room', models.CharField(blank=True, help_text='Excel ROOM e.g. B, C', max_length=50, null=True)),
                ('quantity', models.IntegerField(default=1, help_text='Excel TOTAL count')),
                ('condition', models.CharField(default='GOOD', max_length=50)),
                ('maintenance_status', models.CharField(default='OPERATIONAL', max_length=50)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('remark', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('machine_code', models.CharField(help_text='Excel NAME e.g. TP 1, TP 2', max_length=50, unique=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('building', models.CharField(default='B1', help_text='e.g. B1, B2', max_length=50)),
                ('room', models.CharField(blank=True, help_text='Excel room e.g. B, B1', max_length=50, null=True)),
                ('product_type', models.CharField(blank=True, help_text='Excel TYPE OF PRODUCT e.g. CUT', max_length=100, null=True)),
                ('place', models.CharField(blank=True, help_text='Excel place e.g. B1', max_length=50, null=True)),
                ('health', models.CharField(choices=[('NORMAL', 'Normal'), ('NEEDS_SERVICE', 'Needs Service'), ('CRITICAL', 'Critical')], default='NORMAL', max_length=20)),
                ('most_frequent_issue', models.CharField(blank=True, help_text='Excel MOST ISSUE e.g. BOLOJA, BELT, GEAR', max_length=100, null=True)),
                ('service_time', models.DateTimeField(blank=True, help_text='Excel SERVICE TIME', null=True)),
                ('last_service_date', models.DateField(blank=True, null=True)),
                ('next_service_date', models.DateField(blank=True, null=True)),
                ('performance_score', models.DecimalField(decimal_places=2, default=1.0, help_text='Performance decimal 0.00 to 1.00 e.g. 0.98, 0.45', max_digits=4, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('total', models.IntegerField(default=1, help_text='Excel TOTAL count')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('MAINTENANCE', 'Under Maintenance'), ('OFFLINE', 'Offline')], default='ACTIVE', max_length=20)),
                ('remark', models.CharField(blank=True, help_text='Excel REMARK e.g. good, imp', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('machine_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='machines', to='assets.machinetype')),
            ],
            options={
                'ordering': ['machine_code'],
            },
        ),
        migrations.CreateModel(
            name='SparePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(help_text='e.g. MLACH, CHINGA, ADJESTER, SPRING, HEATER, Red Belt', max_length=100)),
                ('for_machine_text', models.CharField(blank=True, help_text="Excel 'for machine' raw text", max_length=100, null=True)),
                ('place', models.CharField(blank=True, help_text='Excel place e.g. R1', max_length=50, null=True)),
                ('room', models.CharField(blank=True, help_text='Excel room e.g. R11', max_length=50, null=True)),
                ('shelf', models.CharField(blank=True, help_text='Excel shelf e.g. AF', max_length=50, null=True)),
                ('quantity', models.DecimalField(decimal_places=2, default=0.0, help_text='Current in-stock quantity', max_digits=10)),
                ('minimum_stock', models.DecimalField(decimal_places=2, default=3.0, help_text='Threshold for low-stock notification', max_digits=10)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('remark', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('compatible_machine_types', models.ManyToManyField(blank=True, related_name='compatible_spares', to='assets.machinetype')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SparePartInventoryTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('INITIAL_STOCK', 'Initial Stock'), ('PURCHASE', 'Purchase'), ('RECEIPT', 'Receipt'), ('MAINTENANCE_CONSUMPTION', 'Maintenance Consumption'), ('ADJUSTMENT', 'Adjustment'), ('TRANSFER', 'Transfer'), ('RETURN', 'Return')], max_length=30)),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Positive for addition, negative for deduction', max_digits=10)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_by', models.CharField(default='System', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reference_machine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spare_consumptions', to='assets.machine')),
                ('spare_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='assets.sparepart')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UtilityMaintenanceExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('vendor', models.CharField(blank=True, max_length=100, null=True)),
                ('performed_by', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('utility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='assets.utilityequipment')),
            ],
        ),
        migrations.CreateModel(
            name='MachineTypeSparePartCompatibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_slot', models.CharField(blank=True, help_text='PART NO1, PART NO2, etc.', max_length=20, null=True)),
                ('remark', models.CharField(blank=True, max_length=255, null=True)),
                ('machine_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compatibility_entries', to='assets.machinetype')),
                ('spare_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compatibility_entries', to='assets.sparepart')),
            ],
            options={
                'unique_together': {('machine_type', 'spare_part')},
            },
        ),
    ]
