# Generated by Django 5.1.15 on 2026-09-09 06:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawMaterialType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Excel NAME e.g. Polyster yarn', max_length=100, unique=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('unit', models.CharField(default='KG', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_number', models.CharField(help_text='e.g. REQ-2026-00001', max_length=50, unique=True)),
                ('requester_name', models.CharField(max_length=100)),
                ('department', models.CharField(default='PRODUCTION', max_length=50)),
                ('reason', models.TextField(help_text='Reason for request e.g. Phase 1 production')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PARTIALLY_ISSUED', 'Partially Issued'), ('ISSUED', 'Issued'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('approved_by', models.CharField(blank=True, max_length=100, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('issued_by', models.CharField(blank=True, max_length=100, null=True)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StorageLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='e.g. ST 1, ST 2, Store 1, Warehouse A', max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('building', models.CharField(default='B1', max_length=50)),
                ('room', models.CharField(blank=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='RawMaterialVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(help_text='Excel COLOR e.g. black, white, brown, red, gray', max_length=50)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('minimum_stock_kg', models.DecimalField(decimal_places=2, default=25.0, help_text='Threshold for low-stock alert', max_digits=12)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raw_material_variants', to='catalog.color')),
                ('material_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='inventory.rawmaterialtype')),
            ],
            options={
                'unique_together': {('material_type', 'color_name')},
            },
        ),
        migrations.CreateModel(
            name='RawMaterialInventoryTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('INITIAL_STOCK', 'Initial Stock'), ('PURCHASE_RECEIPT', 'Purchase Receipt'), ('PRODUCTION_CONSUMPTION', 'Production Consumption'), ('ADJUSTMENT', 'Adjustment'), ('TRANSFER', 'Transfer'), ('RETURN', 'Return')], max_length=40)),
                ('quantity_kg', models.DecimalField(decimal_places=2, help_text='Positive for addition, negative for consumption', max_digits=12)),
                ('balance_after_kg', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reference_batch_number', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_by', models.CharField(default='System', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='inventory.rawmaterialvariant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('RAW_MATERIAL', 'Raw Material'), ('SPARE_PART', 'Spare Part'), ('OTHER', 'Other')], default='RAW_MATERIAL', max_length=20)),
                ('item_description', models.CharField(blank=True, max_length=255, null=True)),
                ('requested_quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('approved_quantity', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('issued_quantity', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('unit', models.CharField(default='KG', max_length=20)),
                ('raw_material_variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.rawmaterialvariant')),
                ('spare_part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assets.sparepart')),
                ('stock_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.stockrequest')),
            ],
        ),
        migrations.CreateModel(
            name='RawMaterialStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_text', models.CharField(blank=True, help_text="Excel 'place' raw text e.g. ST 1, ST 2", max_length=50, null=True)),
                ('st_v', models.DecimalField(decimal_places=2, default=0.0, help_text='Excel ST V', max_digits=12)),
                ('st_n', models.DecimalField(decimal_places=2, default=0.0, help_text='Excel ST N', max_digits=12)),
                ('total_kg', models.DecimalField(decimal_places=2, default=0.0, help_text='Excel total', max_digits=12)),
                ('available_kg', models.DecimalField(decimal_places=2, default=0.0, help_text='Available KG for production consumption', max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_records', to='inventory.rawmaterialvariant')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='raw_material_stocks', to='inventory.storagelocation')),
            ],
        ),
    ]
