# Generated by Django 5.1.15 on 2026-09-09 06:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('catalog', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch_number', models.CharField(help_text='e.g. BATCH-2026-00001', max_length=50, unique=True)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('IN_PROGRESS', 'In Progress'), ('PHASE_1_COMPLETE', 'Phase 1 Complete'), ('TRANSFERRED', 'Transferred to Building 2'), ('PHASE_2_IN_PROGRESS', 'Phase 2 In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PLANNED', max_length=30)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('supervisor', models.CharField(blank=True, max_length=100, null=True)),
                ('raw_yarn_input_kg', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('braided_output_kg', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('phase1_waste_kg', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('tipping_input_kg', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('finished_output_kg', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('phase2_waste_kg', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_waste_kg', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('yield_percentage', models.DecimalField(decimal_places=2, default=0.0, help_text='Finished Output / Raw Input * 100', max_digits=6)),
                ('waste_percentage', models.DecimalField(decimal_places=2, default=0.0, help_text='Total Waste / Raw Input * 100', max_digits=6)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_by', models.CharField(default='System', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='catalog.productvariant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Phase2TippingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.CharField(default='Building 2', max_length=50)),
                ('room', models.CharField(default='B2', max_length=50)),
                ('operator', models.CharField(max_length=100)),
                ('input_weight_kg', models.DecimalField(decimal_places=2, max_digits=12)),
                ('finished_output_kg', models.DecimalField(decimal_places=2, max_digits=12)),
                ('waste_kg', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tipping_records', to='assets.machine')),
                ('batch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='phase2_record', to='production.productionbatch')),
            ],
        ),
        migrations.CreateModel(
            name='Phase1BraidingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.CharField(default='Building 1', max_length=50)),
                ('room', models.CharField(default='B1', max_length=50)),
                ('operator', models.CharField(max_length=100)),
                ('input_weight_kg', models.DecimalField(decimal_places=2, max_digits=12)),
                ('output_weight_kg', models.DecimalField(decimal_places=2, max_digits=12)),
                ('waste_kg', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='braiding_records', to='assets.machine')),
                ('raw_material_variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='braiding_records', to='inventory.rawmaterialvariant')),
                ('batch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='phase1_record', to='production.productionbatch')),
            ],
        ),
        migrations.CreateModel(
            name='WIPTransfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_building', models.CharField(default='Building 1', max_length=50)),
                ('source_room', models.CharField(default='B1', max_length=50)),
                ('destination_building', models.CharField(default='Building 2', max_length=50)),
                ('destination_room', models.CharField(default='B2', max_length=50)),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sender', models.CharField(max_length=100)),
                ('receiver', models.CharField(blank=True, max_length=100, null=True)),
                ('transfer_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_TRANSIT', 'In Transit'), ('RECEIVED', 'Received')], default='PENDING', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='production.productionbatch')),
            ],
        ),
    ]
