# Generated by Django 5.1.15 on 2026-09-09 11:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionbatch',
            name='acetone_used',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Acetone consumed in Liters/KG', max_digits=12),
        ),
        migrations.AddField(
            model_name='productionbatch',
            name='film_roll_used',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Film roll consumed in Rolls/KG', max_digits=12),
        ),
        migrations.AddField(
            model_name='productionbatch',
            name='film_roll_variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches_as_film', to='inventory.rawmaterialvariant'),
        ),
        migrations.AddField(
            model_name='productionbatch',
            name='raw_material_yarn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches_as_yarn', to='inventory.rawmaterialvariant'),
        ),
        migrations.AlterField(
            model_name='productionbatch',
            name='raw_yarn_input_kg',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Initial raw yarn weight in KG', max_digits=12),
        ),
        migrations.CreateModel(
            name='ProductionBatchMaterial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit', models.CharField(default='KG', max_length=20)),
                ('phase', models.CharField(choices=[('PHASE_1', 'Phase 1 - Braiding'), ('PHASE_2', 'Phase 2 - Tipping')], default='PHASE_1', max_length=20)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials_used', to='production.productionbatch')),
                ('raw_material_variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batch_usages', to='inventory.rawmaterialvariant')),
            ],
        ),
    ]
