# Generated by Django 5.1.15 on 2026-09-09 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_productionbatch_acetone_used_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionbatch',
            name='stock_request_number',
            field=models.CharField(blank=True, help_text='Linked Inventory Stock Request', max_length=50, null=True),
        ),
    ]
