# Generated by Django 5.1.15 on 2026-09-09 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_productionbatch_stock_request_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionbatch',
            name='yarn_batch_count',
            field=models.IntegerField(default=1, help_text='Number of 32 KG yarn store batches (1 batch = 32 KG, 2 = 64 KG, 3 = 96 KG...)'),
        ),
        migrations.AlterField(
            model_name='productionbatch',
            name='raw_yarn_input_kg',
            field=models.DecimalField(decimal_places=2, default=32.0, help_text='Initial raw yarn weight in KG (batches * 32 KG)', max_digits=12),
        ),
    ]
