# Generated by Django 5.1.15 on 2026-09-09 06:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient', models.CharField(default='admin', help_text='Target role or user e.g. store_manager, maintenance_manager, sales_manager', max_length=100)),
                ('notification_type', models.CharField(choices=[('STOCK_LOW', 'Low Stock'), ('STOCK_REQUEST', 'Stock Request'), ('MAINTENANCE_DUE', 'Maintenance Due'), ('MACHINE_CRITICAL', 'Machine Critical'), ('CREDIT_WARNING', 'Credit Warning'), ('CREDIT_OVERDUE', 'Credit Overdue'), ('HR_ALERT', 'Workforce Exception'), ('SYSTEM', 'System')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical')], default='INFO', max_length=20)),
                ('related_model', models.CharField(blank=True, max_length=100, null=True)),
                ('related_object_id', models.CharField(blank=True, max_length=100, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_name', models.CharField(help_text='e.g. store_manager, maintenance_manager, sales, admin', max_length=100, unique=True)),
                ('notify_low_raw_material', models.BooleanField(default=True)),
                ('notify_low_spares', models.BooleanField(default=True)),
                ('notify_stock_requests', models.BooleanField(default=True)),
                ('notify_machine_critical', models.BooleanField(default=True)),
                ('notify_credit_threshold', models.DecimalField(decimal_places=2, default=80.0, help_text='Threshold % to trigger credit warning', max_digits=5)),
                ('notify_credit_overdue', models.BooleanField(default=True)),
            ],
        ),
    ]
