# Generated by Django 5.1.15 on 2026-09-09 06:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('who', models.CharField(default='System', max_length=100)),
                ('action', models.CharField(help_text='e.g. CREATE, UPDATE, DELETE, DISPATCH, COLLECT_PAYMENT, APPROVE_REQUEST', max_length=50)),
                ('model_name', models.CharField(max_length=100)),
                ('object_id', models.CharField(max_length=100)),
                ('object_repr', models.CharField(blank=True, max_length=255, null=True)),
                ('changes_json', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UniversalMovementLedger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('movement_type', models.CharField(choices=[('RAW_MATERIAL_RECEIPT', 'Raw Material Receipt'), ('RAW_MATERIAL_CONSUMPTION', 'Raw Material Consumption'), ('WIP_OUTPUT', 'WIP Output (Braiding)'), ('WIP_TRANSFER', 'WIP Transfer'), ('FINISHED_GOODS_ENTRY', 'Finished Goods Entry'), ('STORE_TRANSFER', 'Store Transfer'), ('DISPATCH', 'Sales Dispatch'), ('RETURN', 'Return'), ('ADJUSTMENT', 'Inventory Adjustment'), ('SPARE_PART_RECEIPT', 'Spare Part Receipt'), ('SPARE_PART_CONSUMPTION', 'Spare Part Consumption')], max_length=40)),
                ('item_category', models.CharField(help_text='RAW_MATERIAL, WIP, FINISHED_BAG, SPARE_PART', max_length=50)),
                ('item_identifier', models.CharField(max_length=100)),
                ('item_description', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit', models.CharField(default='KG', max_length=20)),
                ('source_location', models.CharField(blank=True, max_length=100, null=True)),
                ('destination_location', models.CharField(blank=True, max_length=100, null=True)),
                ('reference_no', models.CharField(blank=True, max_length=100, null=True)),
                ('performed_by', models.CharField(default='System', max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
