# Generated by Django 5.1.15 on 2026-09-09 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('code', models.CharField(blank=True, help_text='Short code or symbol e.g. B, W, -', max_length=20, null=True)),
                ('hex_code', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(default='SHOE_LACE', max_length=100)),
                ('unit', models.CharField(default='KG', max_length=20)),
                ('remark', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Thickness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. 3MM, 10MM, 15MM', max_length=50, unique=True)),
                ('value_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_code', models.CharField(help_text='Excel SERRIAL CODE e.g. 37\\110, 37\\k, 40 cm', max_length=100)),
                ('specification', models.CharField(blank=True, max_length=100, null=True)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_variants', to='catalog.color')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.product')),
                ('thickness', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_variants', to='catalog.thickness')),
            ],
            options={
                'unique_together': {('serial_code', 'color', 'thickness')},
            },
        ),
        migrations.CreateModel(
            name='ProductStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_product', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('in_qty', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('out_qty', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('st_v', models.DecimalField(decimal_places=2, default=0.0, help_text='Excel ST V', max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, help_text='Excel Total / Opening Stock', max_digits=12)),
                ('calculated_stock', models.DecimalField(decimal_places=2, default=0.0, help_text='Ledger-derived current stock', max_digits=12)),
                ('remark', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('variant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='catalog.productvariant')),
            ],
        ),
    ]
