# Generated by Django 5.1.15 on 2026-09-09 06:55

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinishedProductBag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bag_id', models.CharField(db_index=True, help_text='e.g. ABSL-2026-000001', max_length=50, unique=True)),
                ('weight_kg', models.DecimalField(decimal_places=2, help_text='Mandatory range: 25.00 KG to 40.00 KG', max_digits=6, validators=[django.core.validators.MinValueValidator(25.0, message='Bag weight must be at least 25.00 KG.'), django.core.validators.MaxValueValidator(40.0, message='Bag weight cannot exceed 40.00 KG.')])),
                ('store_location', models.CharField(default='Finished Goods Store 1', max_length=100)),
                ('status', models.CharField(choices=[('IN_STORE', 'In Store'), ('RESERVED', 'Reserved'), ('DISPATCHED', 'Dispatched'), ('RETURNED', 'Returned'), ('DAMAGED', 'Damaged')], db_index=True, default='IN_STORE', max_length=20)),
                ('entry_date', models.DateField(auto_now_add=True)),
                ('dispatched_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_by', models.CharField(default='System', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bags', to='production.productionbatch')),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finished_bags', to='catalog.productvariant')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoreMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('movement_type', models.CharField(choices=[('STORE_ENTRY', 'Store Entry'), ('STORE_TRANSFER', 'Store Transfer'), ('STORE_RESERVATION', 'Store Reservation'), ('DISPATCH', 'Dispatch'), ('RETURN', 'Return'), ('DAMAGE', 'Damage'), ('ADJUSTMENT', 'Adjustment')], max_length=30)),
                ('from_location', models.CharField(blank=True, max_length=100, null=True)),
                ('to_location', models.CharField(blank=True, max_length=100, null=True)),
                ('reference_order', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_by', models.CharField(default='System', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='store.finishedproductbag')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='finishedproductbag',
            constraint=models.CheckConstraint(condition=models.Q(('weight_kg__gte', 25.0), ('weight_kg__lte', 40.0)), name='valid_bag_weight_range'),
        ),
    ]
