# Generated by Django 5.1.15 on 2026-09-09 12:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('production', '0004_productionbatch_yarn_batch_count_and_more'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='finishedproductbag',
            name='valid_bag_weight_range',
        ),
        migrations.AlterField(
            model_name='finishedproductbag',
            name='weight_kg',
            field=models.DecimalField(decimal_places=2, help_text='Measured sack scale weight in KG', max_digits=8, validators=[django.core.validators.MinValueValidator(0.01, message='Bag weight must be greater than 0 KG.')]),
        ),
        migrations.AddConstraint(
            model_name='finishedproductbag',
            constraint=models.CheckConstraint(condition=models.Q(('weight_kg__gt', 0)), name='valid_bag_weight_positive'),
        ),
    ]
