# Generated by Django 5.1.15 on 2026-09-23 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='Designated customer record for customer / store role', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profiles', to='sales.customer'),
        ),
    ]
