# Generated by Django 5.1.15 on 2026-09-09 06:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentRegistry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_number', models.CharField(blank=True, help_text='Excel docx no', max_length=50, null=True)),
                ('document_name', models.CharField(help_text='Excel name of docx', max_length=255)),
                ('room', models.CharField(blank=True, help_text='Excel room', max_length=50, null=True)),
                ('shelf', models.CharField(blank=True, help_text='Excel shelf', max_length=50, null=True)),
                ('docx_no', models.CharField(blank=True, help_text='Excel docx no', max_length=50, null=True)),
                ('document_type', models.CharField(choices=[('CERTIFICATE', 'Certificate'), ('POLICY', 'Company Policy / Agreement'), ('REPORT', 'Audit / Inspection Report'), ('CONTRACT', 'Contract / Deal Book'), ('MANUAL', 'Machine Manual'), ('OTHER', 'Other')], default='OTHER', max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/')),
                ('uploaded_by', models.CharField(default='System', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['document_name'],
            },
        ),
    ]
