# Generated by Django 5.1.15 on 2026-09-09 06:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalPaymentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Excel PAYMENT e.g. SATURDAY', max_length=100, unique=True)),
                ('means', models.CharField(default='WEEKLY', help_text='Excel MEANS e.g. WEEKLY, MONTHLY', max_length=50)),
                ('default_price', models.DecimalField(decimal_places=2, default=1800.0, help_text='Excel PRICE in ETB', max_digits=12)),
                ('target_group', models.CharField(default='F.I.A', help_text='Excel FOR WHO e.g. F.I.A', max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employee_id', models.CharField(db_index=True, help_text='e.g. EMP-0001', max_length=50, unique=True)),
                ('name', models.CharField(help_text='Excel NAME OF LABOR e.g. SELEHADIN ALI, ISHAQ ALEMAYEW', max_length=150)),
                ('age', models.IntegerField(blank=True, help_text='Excel AGE', null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', help_text='Excel GENDER', max_length=10)),
                ('work_hours_per_day', models.IntegerField(default=8, help_text='Excel WORK HOUR')),
                ('work_room', models.CharField(blank=True, help_text='Excel WORK ROOM e.g. B1, B2, ALL', max_length=100, null=True)),
                ('base_salary', models.DecimalField(decimal_places=2, default=0.0, help_text='Excel SALLARY in ETB', max_digits=12)),
                ('performance_score', models.DecimalField(decimal_places=2, default=80.0, help_text='Excel PERFORMANCE e.g. 85, 90', max_digits=6)),
                ('employment_status', models.CharField(choices=[('ACTIVE', 'Active'), ('ON_LEAVE', 'On Leave'), ('TERMINATED', 'Terminated')], default='ACTIVE', max_length=20)),
                ('hire_date', models.DateField(blank=True, null=True)),
                ('remark', models.CharField(blank=True, help_text='Excel REMARK', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PayrollConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Standard Factory Payroll Rule', max_length=100)),
                ('salary_period', models.CharField(choices=[('MONTHLY', 'Monthly'), ('WEEKLY', 'Weekly'), ('CUSTOM', 'Custom')], default='MONTHLY', max_length=20)),
                ('working_days_per_period', models.PositiveIntegerField(default=26, help_text='Standard factory working days per month')),
                ('absence_deduction_method', models.CharField(choices=[('DAILY_RATE', 'Daily Rate (Salary / Working Days * Absent Days)'), ('PERCENTAGE_OF_SALARY', 'Percentage (Salary * Configured % * Absent Days)'), ('FIXED_AMOUNT', 'Fixed Amount per Absent Day')], default='DAILY_RATE', max_length=30)),
                ('absence_deduction_rate', models.DecimalField(decimal_places=4, default=0.0385, help_text='Used if PERCENTAGE (e.g. 0.0385 for 3.85%) or FIXED_AMOUNT (e.g. 300 ETB)', max_digits=10)),
                ('overtime_hourly_multiplier', models.DecimalField(decimal_places=2, default=1.25, help_text='1.25x hourly rate', max_digits=5)),
                ('saturday_rate', models.DecimalField(decimal_places=2, default=1800.0, help_text='Weekly Saturday allowance in ETB', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('effective_from', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PayrollPeriod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_code', models.CharField(help_text='e.g. PAYROLL-2026-09', max_length=50, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('working_days', models.PositiveIntegerField(default=26)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('CALCULATED', 'Calculated'), ('APPROVED', 'Approved'), ('PAID', 'Paid')], default='DRAFT', max_length=20)),
                ('config_snapshot', models.JSONField(blank=True, help_text='Permanent snapshot of payroll rules used for historical integrity', null=True)),
                ('total_gross_salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('total_net_salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('created_by', models.CharField(default='System', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeAdditionalPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('effective_date', models.DateField()),
                ('active', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='additional_payments', to='workforce.employee')),
                ('payment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workforce.additionalpaymenttype')),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('LATE', 'Late'), ('HALF_DAY', 'Half Day'), ('LEAVE', 'Approved Leave')], default='PRESENT', max_length=20)),
                ('check_in', models.TimeField(blank=True, null=True)),
                ('check_out', models.TimeField(blank=True, null=True)),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('overtime_allowance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_saturday', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_by', models.CharField(default='System', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='workforce.employee')),
            ],
            options={
                'ordering': ['-date', 'employee__name'],
                'unique_together': {('employee', 'date')},
            },
        ),
        migrations.CreateModel(
            name='PayrollSlip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('base_salary', models.DecimalField(decimal_places=2, max_digits=12)),
                ('working_days', models.PositiveIntegerField(default=26)),
                ('present_days', models.PositiveIntegerField(default=26)),
                ('absent_days', models.PositiveIntegerField(default=0)),
                ('late_days', models.PositiveIntegerField(default=0)),
                ('leave_days', models.PositiveIntegerField(default=0)),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('overtime_pay', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('saturday_pay', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('additional_allowances', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('absence_deduction', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('other_deductions', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('net_salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('calculation_details', models.JSONField(blank=True, help_text='Transparent calculation step-by-step breakdown', null=True)),
                ('status', models.CharField(default='CALCULATED', max_length=20)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payroll_slips', to='workforce.employee')),
                ('payroll_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slips', to='workforce.payrollperiod')),
            ],
            options={
                'ordering': ['employee__name'],
                'unique_together': {('payroll_period', 'employee')},
            },
        ),
    ]
