# Generated by Django 5.1.15 on 2026-09-09 06:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_code', models.CharField(db_index=True, help_text='e.g. CUST-001', max_length=50, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('customer_type', models.CharField(choices=[('RETAIL_SHOP', 'Retail Shop'), ('WHOLESALER', 'Wholesaler'), ('DISTRIBUTOR', 'Distributor')], default='WHOLESALER', max_length=30)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('contact_person', models.CharField(blank=True, max_length=100, null=True)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=0.0, help_text='Maximum allowed credit in ETB', max_digits=14)),
                ('current_outstanding', models.DecimalField(decimal_places=2, default=0.0, help_text='Current unpaid debt in ETB', max_digits=14)),
                ('active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DispatchOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_number', models.CharField(db_index=True, help_text='e.g. DISP-2026-00001', max_length=50, unique=True)),
                ('payment_mode', models.CharField(choices=[('CASH', 'Cash'), ('CREDIT', 'Credit')], default='CASH', max_length=20)),
                ('total_kg', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Total order amount in ETB', max_digits=14)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('outstanding_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Dispatch'), ('COMPLETED', 'Dispatched'), ('PARTIAL', 'Partially Paid'), ('SETTLED', 'Settled / Fully Paid'), ('OVERDUE', 'Overdue'), ('CANCELLED', 'Cancelled')], default='COMPLETED', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_by', models.CharField(default='System', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispatch_orders', to='sales.customer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DispatchOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=6)),
                ('price_per_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=14)),
                ('bag', models.OneToOneField(help_text='Guarantees a bag is never dispatched twice', on_delete=django.db.models.deletion.PROTECT, related_name='dispatch_record', to='store.finishedproductbag')),
                ('dispatch_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.dispatchorder')),
            ],
        ),
        migrations.CreateModel(
            name='Receivable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=14)),
                ('remaining_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PARTIAL', 'Partially Paid'), ('SETTLED', 'Settled'), ('OVERDUE', 'Overdue')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receivables', to='sales.customer')),
                ('dispatch_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receivable', to='sales.dispatchorder')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('payment_date', models.DateField()),
                ('payment_method', models.CharField(choices=[('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank Transfer (CBE / Awash)'), ('CHEQUE', 'Cheque'), ('TELEBIRR', 'Telebirr')], default='CASH', max_length=30)),
                ('reference_no', models.CharField(blank=True, help_text='Cheque / bank transaction slip number', max_length=100, null=True)),
                ('recorded_by', models.CharField(default='System', max_length=100)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('receivable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='sales.receivable')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
